SendToConsole("mp_respawn_on_death_t 1")
SendToConsole("mp_respawn_on_death_ct 1")
SendToConsole("mp_ignore_round_win_conditions 1")
SendToConsole("mp_teammates_are_enemies 1")
SendToConsole("mp_warmup_end")
