SendToConsole("sv_cheats 1");
SendToConsole("ent_remove GORP_Script");
SendToConsole("ent_remove GORP_Timer");
SendToConsole("sv_cheats 0");

GORP_Script <- Entities.CreateByClassname("logic_script");
GORP_Script.__KeyValueFromString("targetname", "GORP_Script");
SendToConsole("echo GORP script scope created");
GORP_Script.__KeyValueFromString("vscripts", "gorp/core.nut");
SendToConsole("echo Loading GORP core script...");
GORP_Script.__KeyValueFromString("thinkfunction", "Think");
SendToConsole("echo Initializing think function...");
GORP_Script.ValidateScriptScope();
SendToConsole("echo GORP script scope validated once");
EntFireByHandle(GORP_Script, "RunScriptFile", "gorp/core", 0.0, GORP_Script, GORP_Script);
SendToConsole("echo GORP script file has ran");
GORP_Script.ValidateScriptScope();
SendToConsole("echo GORP script scope validated twice");
	
GORP_Timer <- Entities.CreateByClassname("logic_timer");
SendToConsole("echo Timer created");
GORP_Timer.__KeyValueFromInt("RefireTime", 1);
SendToConsole("echo Refire time set");
GORP_Timer.__KeyValueFromString("targetname", "GORP_Timer");
GORP_Timer.ValidateScriptScope();
SendToConsole("echo Timer scope validated");
SendToConsole("sv_cheats 1");
SendToConsole("ent_fire GORP_Timer enable");
SendToConsole("ent_fire GORP_Timer addoutput \"startdisabled 0\"");
SendToConsole("ent_fire GORP_Timer addoutput \"OnTimer GORP_Script,RunScriptCode,Think(),0.0,-1\"");
SendToConsole("sv_cheats 0");
